# -*- coding: utf-8 -*-
"""
Django settings for d project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Buid paths inside the project like this: os.path.join(BASE_DIR, ...)
import os







BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gplb7627lwe1$m!qa3#=pllpqjd1nm2u%mr3u2t4^8soen92@3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    # material apps
    #'material',
    #'material.frontend',
    #'easy_pjax',
    #'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qa',
    # 标签app
    'tagging',
    # endless-pagination
    'endless_pagination',
    
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #material
    #'material.frontend.middleware.SmoothNavigationMiddleware',
)

ROOT_URLCONF = 'd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 注册上自定义的全局标签
                'qa.views.global_setting'
                #material 
                #'material.frontend.context_processors.modules',
            ],
        },
    },
]

WSGI_APPLICATION = 'd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : 'mysite',
        'USER' : 'root',
        'PASSWORD': '0',
        'HOST' :'localhost',
        'PORT': '3306',
        'charset':'utf8',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#静态文件路径,必须是一个列表
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
#  自定义上传路径
MEDIA_URL = '/uploads/'
# 上传的绝对路径
MEDIA_ROOT = os.path.join(BASE_DIR,'uploads')
# 自定义用户model
AUTH_USER_MODEL = 'qa.User'
# 站点信息配置
SITE_URL = 'http://127.0.0.1:8000'


# 无限刷新页面的设置

ENDLESS_PAGINATION_PER_PAGE = 3
 #--加载样式的设定--
ENDLESS_PAGINATION_LOADING = """ <div class="loader-inner line-scale-pulse-out"><div></div><div></div><div></div><div></div><div></div></div>"""